# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['docker.local:9091','host.docker.internal:9091','10.254.254.254:9091']
global:
  scrape_interval:     2s
  evaluation_interval: 4s
